### ISSUE TITLE
Client unexpected eof (age=0)

### ISSUE THREAD

**Issue by Kronuz** [pgbouncer/pgbouncer#323]
When using Kubernetes (or other ways to maintain pgbouncer reliably service up and running), there is always the need to know if the pgbouncer server is still running. Kubernetes uses "`livenessProbe`" to check if the service is still responding to TCP requests. However, it only checks if it can open the TCP port and closes it; this results in a bunch of logged errors by pgbouncer, as such: `LOG C-0x55b321680410: (nodb)/(nouser)@10.56.0.1:34772 closing because: client unexpected eof (age=0)`

I suggest making it so when `(age=0)` it (perhaps optionally) ignores an open/close connection so this doesn't happen.

Maybe we could add an option for this, or maybe we could simply ignore open/close connections altogether.

**Comment by ebarault** [comment]
using aws ecs cluster here and having the exact same issue, the logs are crippled by `Client unexpected eof (age=0)` errors because of the TCP health_check on pgbouncer port

**Comment by carmelid** [comment]
Using Kubernetes on GCP and are also feeling that the cluster log output are crippled by the amount of error logs from pgbouncer. Has anyone been able to find a solution/resolve this?

**Comment by VSpike** [comment]
You could create a custom healthcheck that serves HTTP on /healthz and connects to the `pgbouncer` database to do a `SHOW USERS` or similar. I'm testing this out as a solution at the moment.

**Comment by BernhardLenz** [comment]
@VSpike Could you please share your healthcheck solution? We've been running without a health check leaving us a bit uneasy...

**Comment by bpatton00** [comment]
@VSpike  
Was anyone able to successful navigate this ?  If so can you share the solution and/or code?

**Comment by VSpike** [comment]
I'm just getting my code reviewed internally to see if it's OK to make the repo open

**Comment by petere** [comment]
Don't you have the same problem with a PostgreSQL server? If you just open and close a TCP/IP connection there, you get log entries like `LOG:  could not receive data from client: Connection reset by peer`.

I think if you want to check whether PgBouncer is truly alive, you need to connect and actually do something. Just checking that the port is open won't tell you much.

**Comment by tamsky** [comment]
@VSpike even if you can't provide an update on opening up your code/repo...

could you at least share and describe the strategy you've got working?

**Comment by VSpike** [comment]
Here you go! https://github.com/deliveroo/pgbouncer-healthcheck
Hope it's useful. My first Golang project, so please excuse the messy history.

**Comment by rehf27** [comment]
With the suggested health check, you end up trading **one log message for two** for login and logout of the user.

**Comment by BhuviTheDataGuy** [comment]
Im not using any load balancer or Kubernetes. I have deployed the pgbouncer on a VM, but Im also getting this error. 

```bash
closing because: client unexpected eof (age=5s)
```

Does anyone find the reason for it?

**Comment by pgodfrin** [comment]
We are having the same issue. Why is the "the need to know if the pgbouncer server is still running" ? First of all, if that need is true, then an option for the frquency is reasonable. But in reality if pgbouncer is not running, wouldn't an error message trap suffice? I don't know if that's possible, but polling seems an immature way to accomplish this.

**Comment by landryb** [comment]
thanks a lot @petere ! much appreciated to discover this feature in 1.15 !

**Comment by salper** [comment]
For the record, I still get these noisy logs on AWS, probably due to the Network Load Balancer health check:
```shell
2021-04-28 15:04:46.007 UTC [1] LOG C-0x7fa7527654d0: (nodb)/(nouser)@xxx.xx.x.x:5761 closing because: client unexpected eof (age=0s)
```

**Comment by kripod** [comment]
I’m not entirely sure if this is related, but setting `tcp_keepidle = 300` [might help](https://blog.cskr.dev/posts/pgbouncer-nlb-connection-leak/), as AWS Network Load Balancer [has a TCP idle timeout of 350s](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout), which is way lower than the expected default of 7200s.

**Comment by livegenic-akyrychek** [comment]
have the issue been fixed  with the noisy logger? Coz i seem to get the same stuff

**Comment by rosehsu47** [comment]
same here
Still getting  
```
(nodb)/(nouser)@XXXXXXX closing because: client unexpected eof (age=0s)
```

using image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
pool mode: transaction
