### ISSUE TITLE
"closing because: server_lifetime" vs  "server lifetime over"

### ISSUE THREAD

**Issue by lohengrin1870** [pgbouncer/pgbouncer#697]
Hello

I see some messages in the pgbouncer.log regarding the parameter server_lifetime exceeded, is there a difference between 
`2022-03-18 12:51:23.580 CET [3031] LOG S-0x13d5b40: db012a21/l_s012a21_transac01@unix:5432 closing because: server_lifetime (age=3612s)`

and 

`2022-03-18 12:52:26.911 CET [3031] LOG S-0x13cf2f8: db709a00/o_s709a00_owner@unix:5432 closing because: server lifetime over (age=3600s)`

Also the parameter has a value of 3600s why I am seeing some messages exceeding this value much higher like 
`2022-03-18 12:28:47.784 CET [3031] LOG S-0x10f91f8: db060a00/l_s060a00_transac01@unix:5432 closing because: server_lifetime (age=5322s)
2022-03-18 12:32:35.725 CET [3031] LOG S-0x10f48c0: db053a00/l_s053a00_transac01@unix:5432 closing because: server_lifetime (age=5369s)
2022-03-18 12:33:20.230 CET [3031] LOG S-0x13d1f58: db060a00/l_s060a00_transac01@unix:5432 closing because: server_lifetime (age=5344s)
`

Thank you in advance

**Comment by Melkij** [comment]
Hi
server_lifetime should not affect client connections. This means that the connection to the server will not be closed as long as it is connected to any client.
By source code, `server lifetime over` is written from periodic check, `closing because: server_lifetime` - immediately on release this server connection (session/transaction/statement was completed, according to pool_mode). Both checks will close connections to the server with some amount of time in between, rather than multiple connections at the same time.

**Comment by petere** [comment]
The error message discrepancy was fixed in 6a9cffe2.

**Comment by lohengrin1870** [comment]
Hi
OK but why there are some message saying that the time is much much bigger than the server_lifetime value set ?
`2022-03-18 12:28:47.784 CET [3031] LOG S-0x10f91f8: db060a00/l_s060a00_transac01@unix:5432 closing because: server_lifetime (age=5322s)`

age=5322s much bigger than 3600s I think it causes confusion

**Comment by petere** [comment]
As was explained, `server_lifetime` doesn't mean that the server connection is killed immediately when the lifetime is reached. It just means that when the server is freed, then it is checked whether the server should be reused or disconnected. So say you use session pooling and you have a session open for 5322 s, then server_lifetime=3600 still has to wait until the session is closed before it can decide to close the server connection.

**Comment by lohengrin1870** [comment]
OK but that's still not clear. 

As I understand the documentation
`The pooler will close an unused (not currently linked to any client connection) server connection that has been connected longer than this.` So it means to me that the client has already disconnected for whatever reason and PGBouncer keeps this connection just in case it needs it.
`So say you use session pooling and you have a session open for 5322 s, then server_lifetime=3600 still has to wait until the session is closed before it can decide to close the server connection.`
Which session are you talking about, the pgbouncer session ? Why the pgbouncer session is waiting so much time to close ?

**Comment by lohengrin1870** [comment]
I will ask another way, here tonigh I have this message :
`2022-03-25 02:34:43.765 CET [14047] LOG S-0xc51588: db732a00/o_s732a00_owner@unix:5432 closing because: server_lifetime (age=3726s)`

So it's a connection which should have started 3726s ago

# select '2022-03-25 02:34:43.765 CET'::timestamp - interval '3726s';
┌─────────────────────────┐
│        ?column?         │
├─────────────────────────┤
│ 2022-03-25 01:32:37.765 │
└─────────────────────────┘
(1 row)`

Looking at the logs at this time :

> 2022-03-25 01:32:37.427 CET [14047] LOG C-0xd267a0: db732a00/o_s732a00_owner@10.150.22.162:42158 closing because: client close request (age=283s)
2022-03-25 01:32:37.427 CET [14047] LOG S-0xc51588: db732a00/o_s732a00_owner@unix:5432 closing because: server_lifetime (age=3727s)
2022-03-25 01:32:37.471 CET [14047] LOG C-0xd267a0: db732a00/o_s732a00_owner@10.150.22.162:43632 login attempt: db=db732a00 user=o_s732a00_owner tls=TLSv1.2/ECDHE-RSA-AES128-GCM-SHA256/ECDH=prime256v1
2022-03-25 01:32:37.610 CET [14047] LOG S-0xc51588: db732a00/o_s732a00_owner@unix:5432 new connection to server 



The address S-0xc51588 is first closed because of the server_lifetime parameter, there is a new login attempt and the same address is reused to open the new connection to the server. Which will be closed later.

**Comment by lohengrin1870** [comment]
> That's probably because when it frees a server connection and then starts a new one, the new one will end up at the same memory address as the previous one. So the new one is actually a new server connection, but it happens to use the same address as the one before.
OK but that doesn't explain why the server connection is closed every 3726s-3727s instead of 3600s 

2022-03-25 01:32:37.427 CET [14047] LOG S-0xc51588: db732a00/o_s732a00_owner@unix:5432 closing because: server_lifetime (age=**3727s**)
2022-03-25 02:34:43.765 CET [14047] LOG S-0xc51588: db732a00/o_s732a00_owner@unix:5432 closing because: server_lifetime (age=**3726s**)


`So say you use session pooling and you have a session open for 5322 s, then server_lifetime=3600 still has to wait until the session is closed before it can decide to close the server connection.` 

We have set the idle_in_transaction_session_timeout parameter to 5 min so I don't understand on this example why I have a difference of 3726 or 27 - 3600 = 126 or 127 is it related to a client timeout ? But as said in the doc the server_lifetime should not be currently linked to any client connection to be effective.

**Comment by petere** [comment]
Please provide a self-contained test configuration for this.

**Comment by eulerto** [comment]
The OP didn't provide the configuration but a possible explanation is:

https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/objects.c#L1146-L1155

This logic was added near the time this issue was created. See commit 2872261b. I don't know if the OP was testing 1.16 or earlier and then tested with 1.17 (that the commit refers to).
